# Generated by Django 2.1.7 on 2019-03-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('clg', models.CharField(max_length=255)),
                ('mob', models.CharField(max_length=255)),
                ('qstn_ans_on', models.DateTimeField()),
                ('q1', models.BooleanField(default=False)),
                ('q2', models.BooleanField(default=False)),
                ('q3', models.BooleanField(default=False)),
                ('q4', models.BooleanField(default=False)),
                ('q5', models.BooleanField(default=False)),
                ('q6', models.BooleanField(default=False)),
            ],
        ),
    ]
