# Generated by Django 2.1.7 on 2019-03-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190322_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='qstn_ans_on',
            new_name='q1_ans_on',
        ),
        migrations.AddField(
            model_name='game',
            name='q2_ans_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='q3_ans_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='q4_ans_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='q5_ans_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='q6_ans_on',
            field=models.DateTimeField(null=True),
        ),
    ]
